### ISSUE TITLE
Link to reference for OCR implementation is broken

### ISSUE THREAD

**Issue by kler** [barsoom/banktools-se#5]
The link on line 1 in `lib/banktools-se/ocr.rb` is broken (guess BGC moved it):
http://www.bgc.se/upload/Gemensamt/Trycksaker/Manualer/BG6070.pdf

It would have been nice if the source code was updated with a working link.
I've tried to find the original document myself, but haven't found it.

**Comment by henrik** [comment]
Good catch, thank you! Will see if I can track it down.

**Comment by henrik** [comment]
I was able to find the document (as of 2011-12-16) here: http://web.archive.org/web/20111216065227/http://www.bgc.se/upload/Gemensamt/Trycksaker/Manualer/BG6070.pdf

**Comment by henrik** [comment]
Found new documents, see referenced commit.
